---
title: "Démonstrateur ASPE : Eléments Peuplement 1 point"
author: "Pascal Irz"
date: "`r format(Sys.time(), 'Le %d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Chargement des packages et des données

```{r}
library(aspe)
library(tidyverse)
```


```{r, echo = FALSE}
load(file = "../processed_data/df1.RData")
load(file = "../processed_data/df2.RData")
load(file = "../processed_data/captures_et_env.RData")
```

```{r, eval = FALSE}
load(file = "processed_data/df1.RData")
load(file = "processed_data/df2.RData")
load(file = "processed_data/captures_et_env.RData")
```


# Définition de la palette de couleurs

```{r}
coul_contrast <- RColorBrewer::brewer.pal(n = 8, name = "Dark2")
coul_pastel <- RColorBrewer::brewer.pal(n = 8, name = "Pastel1")

mon_theme <-
  theme(
    panel.background = element_rect(fill = coul_pastel[2]),
    panel.grid.major = element_line(colour = coul_pastel[3]),
    panel.grid.minor = element_line(colour = coul_pastel[3],
                                    linetype = 'dotted',
                                    size = 0.7)
  )
```

```{r}
mon_pop <- "10603"
capt_mef_colo_ext <- mef_colo_ext_pops(df = df1,
                                       id_point = mon_pop)
```



```{r}
gg_colo_ext_pops(capt_mef_colo_ext)
```
```{r}

```

```{r}
esp_communes <- pres_abs_env %>% 
  filter(presences > 1000) %>% 
  pull(esp_code_alternatif) %>% 
  unique %>% 
  as.character

captures_et_env <- captures_et_env %>% 
  filter(esp_code_alternatif %in% esp_communes)
```


```{r}
gg_density_env_pres_abs_nparam <- function(df, espece, parametres = NA, quantile_max = 0.99,
                                           log = c('surface_bv', 'distance_source', 'pente'))
  
{
  
  if (is.na(parametres))
{
  parametres <- df %>%
    pull(parametre) %>%
    unique() %>% 
    as.character
  }

gg_density_env_pres_abs <- function(parametre, df, espece) 
  
{
  data <- df %>% 
  filter(esp_code_alternatif == espece,
         parametre == !!parametre)  # force l'évaluation en premier lieu / synonymie
  
  x_max <- data %>% 
    pull(valeur_parametre) %>% 
    quantile(probs = c(quantile_max))
  
plot <-
  ggplot(data = data,
         aes(x = valeur_parametre,
             fill = presence)) +
    geom_density(alpha = 0.1) +
    labs(x = parametre,
         y = "Densité",
         title = espece) +
    scale_x_continuous(limits = c(NA, x_max))

if(!!parametre %in% log) {
  plot <- plot + scale_x_log10()
}

plot
    
  
}



map(.x = parametres,
    .f = gg_density_env_pres_abs,
    df = df,
    espece = espece)
}
```

```{r}
gg_density_env_pres_abs(df = captures_et_env,
                        espece = "BRE",
                        parametre = "altitude")
```


```{r}
gg_density_env_pres_abs_nparam(df = captures_et_env,
                        espece = "BRE")

```




```{r, fig.width = 10, fig.height = 10}


gg_evol_env_esp <- function(df, parametre)
  
{
  
df %>% 
  filter(parametre == parametre) %>% 
  ggplot(aes(x = annee, y = valeur_parametre, col = presence)) +
    geom_smooth(method = "lm") +
    labs(x = "", y = parametre) +
    scale_x_continuous(limits = c(1995, NA)) +
    facet_wrap(~esp_code_alternatif,
               scales = "free_y", ncol = 5)
  
}

parametres <- captures_et_env %>% 
  pull(parametre) %>% 
  unique

map(.x = parametres,
    .f = gg_evol_env_esp,
    df = captures_et_env)

```

Est-ce que les caractéristiques des sites prospectés ont changé au fil des années ?

```{r}
env <- df1 %>%
         select(ope_id, annee) %>%
         distinct() %>%
  left_join(y = operation %>%
              select(ope_id, pop_id = ope_pop_id)) %>% 
  mef_ajouter_ope_env() %>% 
  pivot_longer(
    cols = distance_mer:temp_janvier,
    names_to = "parametre",
    values_to = "valeur_parametre",
    values_drop_na = TRUE
  )

env %>% 
  ggplot(aes(x = annee, y = valeur_parametre)) +
    #geom_boxplot(coef=1e30) +
   geom_smooth(method = "gam") +
    labs(x = "") +
    scale_x_continuous(limits = c(1990, NA)) +
    facet_wrap(~parametre,
               scales = "free_y",
               ncol = 4)
```


```{r}
env %>% 
 # filter(parametre == mon_parametre) %>% 
  ggplot(aes(x = valeur_parametre, y = as.factor(annee))) +
    ggridges::geom_density_ridges() +
 #   labs(x = parametre) +
    facet_wrap(~parametre,
               scales = "free_x")
```



