---
title: "Démonstrateur ASPE : Construction des synthèses par point"
author: "Pascal Irz"
date: "`r format(Sys.time(), 'Le %d %B %Y')`"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Chargement des packages et des données

```{r}
library(aspe)
library(tidyverse)
```


```{r, echo = FALSE}
load(file = "../processed_data/captures.RData")
load(file = "../processed_data/pop_geo.RData")
load(file = "../processed_data/sh_geo.RData")
load(file = "../processed_data/bretagne.RData")
```

```{r, eval = FALSE}
load(file = "processed_data/captures.RData")
load(file = "processed_data/pop_geo.RData")
load(file = "processed_data/sh_geo.RData")
load(file = "processed_data/bretagne")
```

```{r}
mon_pop <- "35803"
capt_mef_colo_ext <- mef_colo_ext_pop(df = captures,
                                      id_point = mon_pop)
```



```{r}
gg_colo_ext_pop(capt_mef_colo_ext)
```
# IPR

```{r}
ipr <- mef_creer_passerelle() %>% 
  ipr_extraire()
```






# Sauvegarde des données préparées

```{r, echo = FALSE}
#save(capt_mef_colo_ext, file = "../processed_data/captures.RData")
```

```{r, eval = FALSE}
#save(capt_mef_colo_ext, file = "processed_data/captures.RData")
```
